// iRacing car + track roster, compiled 2026-09-29 (current through 2026 Season 4).
// Car names: iRacing data-API names (match the in-sim UI / telemetry screen names).
// Track names: iRacing member-portal display strings ('Track - Config' for multi-config
// tracks, plain track name for single-config tracks).
// Sources: iRacing data API (via adrianulima/my-racing-planner, 2026-06-25),
// meowmachine/racing-track-maps-vector portal scrape (2026-05-05),
// iRacing 2026 S3/S4 release notes, iracing.com/cars/, OverTake.gg S4 car/track lists.
// 189 cars, 428 track configs.

export const IRACING_CARS: string[] = [
  '[Legacy] Audi R8 LMS GT3',
  '[Legacy] Audi RS3 LMS TCR',
  '[Legacy] BMW Z4 GT3',
  '[Legacy] Dallara DW12',
  '[Legacy] Dallara IR-05',
  '[Legacy] Ferrari 488 GT3',
  '[Legacy] Gen 4 Cup',
  '[Legacy] Mazda MX-5 Cup - 2010',
  '[Legacy] Mazda MX-5 Roadster - 2010',
  '[Legacy] McLaren MP4-12C GT3',
  '[Legacy] Mercedes-AMG GT3',
  '[Legacy] NASCAR Cup Chevrolet Impala COT - 2009',
  '[Legacy] NASCAR Cup Chevrolet SS - 2013',
  '[Legacy] NASCAR Cup Ford Fusion - 2016',
  '[Legacy] NASCAR Nationwide Chevrolet Impala - 2012',
  '[Legacy] NASCAR Truck Chevrolet Silverado - 2008',
  '[Legacy] NASCAR Xfinity Chevrolet Camaro - 2014',
  '[Legacy] NASCAR Xfinity Ford Mustang - 2016',
  '[Legacy] NASCAR Xfinity Toyota Camry - 2015',
  '[Legacy] Porsche 911 GT3 Cup (991)',
  '[Legacy] Porsche 911 GT3 Cup (992.1)',
  '[Legacy] Porsche 911 GT3 R',
  '[Legacy] Pro Mazda',
  '[Legacy] Riley MkXX Daytona Prototype - 2008',
  '[Legacy] Supercars Ford Mustang GT',
  '[Legacy] Supercars Holden ZB Commodore',
  '[Legacy] V8 Supercar Ford Falcon - 2009',
  '[Legacy] V8 Supercar Ford FG Falcon - 2014',
  '[Legacy] V8 Supercar Holden VF Commodore - 2014',
  'Acura ARX-06 GTP',
  'Acura NSX GT3 EVO 22',
  'ARCA Chevrolet SS',
  'ARCA Ford Mustang',
  'ARCA Menards Chevrolet Impala',
  'ARCA Toyota Camry',
  'Aston Martin DBR9 GT1',
  'Aston Martin Valkyrie AMR-LMH',
  'Aston Martin Vantage GT3 EVO',
  'Aston Martin Vantage GT4',
  'Audi 90 GTO',
  'Audi R18',
  'Audi R8 LMS EVO II GT3',
  'Audi RS3 LMS Gen2 TCR',
  'BMW M Hybrid V8',
  'BMW M2 CS Racing (F87) - 2020',
  'BMW M2 Racing (G87)',
  'BMW M4 F82 GT4 - 2018',
  'BMW M4 G82 GT4 Evo',
  'BMW M4 GT3 EVO',
  'BMW M8 GTE',
  'Cadillac CTS-V Racecar',
  'Cadillac V-Series.R GTP',
  'Caterham 420R',
  'Caterham Academy',
  'Chevrolet Corvette C6.R GT1',
  'Chevrolet Corvette C7 Daytona Prototype',
  'Chevrolet Corvette C8.R GTE',
  'Chevrolet Corvette Z06 GT3.R',
  'Dallara F3',
  'Dallara IL-15',
  'Dallara iR-01',
  'Dallara IR18',
  'Dallara P217',
  'Dirt 358 Modified',
  'Dirt Big Block Modified',
  'Dirt Late Model - Limited',
  'Dirt Late Model - Pro',
  'Dirt Late Model - Super',
  'Dirt Legends Ford \'34 Coupe',
  'Dirt Micro Sprint Car - Non-Winged',
  'Dirt Micro Sprint Car - Winged',
  'Dirt Midget',
  'Dirt Mini Stock',
  'Dirt Outlaw Micro Sprint Car - Non-Winged',
  'Dirt Outlaw Micro Sprint Car - Winged',
  'Dirt Sprint Car - 305',
  'Dirt Sprint Car - 360',
  'Dirt Sprint Car - 360 Non-Winged',
  'Dirt Sprint Car - 410',
  'Dirt Sprint Car - 410 Non-Winged',
  'Dirt Street Stock',
  'Dirt UMP Modified',
  'EURO NASCAR V8GP',
  'Ferrari 296 Challenge',
  'Ferrari 296 GT3',
  'Ferrari 488 GT3 Evo 2020',
  'Ferrari 488 GTE',
  'Ferrari 499P',
  'FIA Cross Car',
  'FIA F4',
  'Ford Fiesta RS WRC',
  'Ford GT GT2',
  'Ford GT GT3',
  'Ford GTE',
  'Ford Mustang FR500S',
  'Ford Mustang GT3',
  'Ford Mustang GT4',
  'Formula Renault 2.0',
  'Formula Renault 3.5',
  'Formula Vee - Classic',
  'Formula Vee - Conqueror',
  'Formula Vee - Cutlass',
  'Gen 4 Chevrolet Monte Carlo - 2003',
  'Gen 4 Ford Taurus - 2003',
  'Gen 4 Grand National',
  'Global Mazda MX-5 Cup',
  'Honda Civic Type R TCR',
  'HPD ARX-01c',
  'Hyundai Elantra N TCR',
  'Hyundai Veloster N TCR',
  'Indy Pro 2000 PM-18',
  'Kia Optima',
  'Lamborghini Huracán GT3 EVO',
  'Late Model Stock',
  'Legends Ford \'34 Coupe',
  'Ligier JS P320',
  'Lotus 49',
  'Lotus 79',
  'Lucas Oil Off Road Pro 2 Lite',
  'Lucas Oil Off Road Pro 2 Truck',
  'Lucas Oil Off Road Pro 4 Truck',
  'McLaren 570S GT4',
  'McLaren 720S GT3 EVO',
  'McLaren MP4-30',
  'Mercedes-AMG GT3 2020',
  'Mercedes-AMG GT4',
  'Mercedes-AMG W12 E Performance',
  'Mercedes-AMG W13 E Performance',
  'Mini Stock',
  'Modified - NASCAR Whelen Tour',
  'Modified - SK',
  'NASCAR Cup Series Chevrolet Camaro ZL1',
  'NASCAR Cup Series Ford Mustang',
  'NASCAR Cup Series Next Gen Chevrolet Camaro ZL1',
  'NASCAR Cup Series Next Gen Ford Mustang',
  'NASCAR Cup Series Next Gen Toyota Camry',
  'NASCAR Cup Series Toyota Camry',
  'NASCAR Legends Buick LeSabre - 1987',
  'NASCAR Legends Chevrolet Monte Carlo - 1987',
  'NASCAR Legends Ford Thunderbird - 1987',
  'NASCAR Legends Pontiac Grand Prix - 1987',
  'NASCAR O\'Reilly Chevrolet Camaro',
  'NASCAR O\'Reilly Ford Mustang',
  'NASCAR O\'Reilly Toyota Supra',
  'NASCAR Truck Chevrolet Silverado',
  'NASCAR Truck Ford F150',
  'NASCAR Truck RAM',
  'NASCAR Truck Toyota Tundra TRD Pro',
  'Nissan GTP ZX-T',
  'Pontiac Solstice',
  'Pontiac Solstice - Rookie',
  'Porsche 718 Cayman GT4 Clubsport MR',
  'Porsche 911 Cup (992.2)',
  'Porsche 911 GT3 R (992)',
  'Porsche 911 RSR',
  'Porsche 919',
  'Porsche 963 GTP',
  'Porsche Mission R',
  'Radical SR10',
  'Radical SR8',
  'Ray FF1600',
  'Renault Clio',
  'Ruf RT 12R AWD',
  'Ruf RT 12R C-Spec',
  'Ruf RT 12R RWD',
  'Ruf RT 12R Track',
  'SCCA Spec Racer Ford',
  'Silver Crown',
  'Skip Barber Formula 2000',
  'Sprint Car',
  'SRX',
  'Stock Car Brasil Chevrolet Cruze',
  'Stock Car Brasil Toyota Corolla',
  'Street Stock - Casino M2',
  'Street Stock - Eagle T3',
  'Street Stock - Panther C1',
  'Subaru WRX STI',
  'Super Formula Lights',
  'Super Formula SF23 - Honda',
  'Super Formula SF23 - Toyota',
  'Super Late Model',
  'Supercars Chevrolet Camaro Gen 3',
  'Supercars Ford Mustang Gen 3',
  'Toyota GR86',
  'USF 2000',
  'VW Beetle',
  'VW Beetle - Lite',
  'VW Jetta TDI Cup',
  'Williams-Toyota FW31'
];

export const IRACING_TRACKS: string[] = [
  '[Legacy] Kentucky Speedway - 2011 - Legends',
  '[Legacy] Kentucky Speedway - 2011 - Oval',
  '[Legacy] Michigan International Speedway - 2009',
  '[Legacy] Phoenix Raceway - 2008 - Dirt Road',
  '[Legacy] Phoenix Raceway - 2008 - Oval',
  '[Legacy] Phoenix Raceway - 2008 - Rallycross',
  '[Legacy] Phoenix Raceway - 2008 - Road Course',
  '[Legacy] Pocono Raceway - 2009 - East',
  '[Legacy] Pocono Raceway - 2009 - International',
  '[Legacy] Pocono Raceway - 2009 - North',
  '[Legacy] Pocono Raceway - 2009 - Oval',
  '[Legacy] Pocono Raceway - 2009 - South',
  '[Legacy] Silverstone Circuit - 2008 - Grand Prix',
  '[Legacy] Silverstone Circuit - 2008 - Historical Grand Prix',
  '[Legacy] Silverstone Circuit - 2008 - International',
  '[Legacy] Silverstone Circuit - 2008 - National',
  '[Legacy] Silverstone Circuit - 2008 - Southern',
  '[Legacy] Texas Motor Speedway - 2009 - Legends Oval',
  '[Legacy] Texas Motor Speedway - 2009 - Oval',
  '[Legacy] Texas Motor Speedway - 2009 - Road Course Combined',
  '[Legacy] Texas Motor Speedway - 2009 - Road Course Long',
  '[Legacy] Texas Motor Speedway - 2009 - Road Course Short A',
  '[Legacy] Texas Motor Speedway - 2009 - Road Course Short B',
  'Adelaide Street Circuit',
  'Algarve International Circuit - Grand Prix',
  'Algarve International Circuit - Grand Prix - Chicanes',
  'Algarve International Circuit - Moto',
  'Algarve International Circuit - Moto - Chicanes',
  'Auto Club Speedway - Competition',
  'Auto Club Speedway - Interior',
  'Auto Club Speedway - Moto',
  'Auto Club Speedway - Oval',
  'Autodromo Internazionale del Mugello - Grand Prix',
  'Autodromo Internazionale del Mugello - Short',
  'Autodromo Internazionale Enzo e Dino Ferrari - Grand Prix',
  'Autodromo Internazionale Enzo e Dino Ferrari - Moto',
  'Autodromo Nazionale Monza - Combined',
  'Autodromo Nazionale Monza - Combined without chicanes',
  'Autodromo Nazionale Monza - Combined without first chicane',
  'Autodromo Nazionale Monza - GP without chicanes',
  'Autodromo Nazionale Monza - GP without first chicane',
  'Autodromo Nazionale Monza - Grand Prix',
  'Autodromo Nazionale Monza - Junior',
  'Autodromo Nazionale Monza - Oval - Left turning',
  'Autodromo Nazionale Monza - Oval - Right turning',
  'Autódromo Hermanos Rodríguez - EV Circuit',
  'Autódromo Hermanos Rodríguez - Grand Prix',
  'Autódromo Hermanos Rodríguez - Grand Prix Historic',
  'Autódromo Hermanos Rodríguez - National',
  'Autódromo Hermanos Rodríguez - National Historic',
  'Autódromo Hermanos Rodríguez - Oval',
  'Autódromo Hermanos Rodríguez - Oval Stadium',
  'Autódromo José Carlos Pace - Grand Prix',
  'Autódromo José Carlos Pace - Moto',
  'Barber Motorsports Park',
  'Bark River International Raceway',
  'Brands Hatch Circuit - Grand Prix',
  'Brands Hatch Circuit - Indy',
  'Brands Hatch Circuit - Rallycross',
  'Bristol Motor Speedway - Dirt',
  'Bristol Motor Speedway - Dirt - 2021',
  'Bristol Motor Speedway - Dual Pit Roads',
  'Bristol Motor Speedway - Single Pit Roads',
  'Cadwell Park Circuit - Club',
  'Cadwell Park Circuit - Full',
  'Cadwell Park Circuit - Moto',
  'Cadwell Park Circuit - Woodlands',
  'Canadian Tire Motorsports Park',
  'Cedar Lake Speedway',
  'Centripetal Circuit',
  'Charlotte Motor Speedway  - Infield Road Course',
  'Charlotte Motor Speedway  - Infield Road Course Long',
  'Charlotte Motor Speedway  - Legends Road Course 2025',
  'Charlotte Motor Speedway  - Oval',
  'Charlotte Motor Speedway  - Rallyx',
  'Charlotte Motor Speedway  - Roval 2019',
  'Charlotte Motor Speedway  - Roval 2025',
  'Charlotte Motor Speedway  - Roval No Chicanes',
  'Charlotte Motor Speedway - Dirt Road',
  'Charlotte Motor Speedway - Legends Oval',
  'Chicago Street Course - 2023 Cup',
  'Chicago Street Course - Prototype',
  'Chicagoland Speedway',
  'Chili Bowl',
  'Circuit de Barcelona Catalunya - Club',
  'Circuit de Barcelona Catalunya - Grand Prix',
  'Circuit de Barcelona Catalunya - Historic',
  'Circuit de Barcelona Catalunya - Moto',
  'Circuit de Barcelona Catalunya - National',
  'Circuit de Barcelona Catalunya - Rallycross',
  'Circuit de Lédenon',
  'Circuit de Nevers Magny-Cours',
  'Circuit de Spa-Francorchamps - Bike',
  'Circuit de Spa-Francorchamps - Classic Pits',
  'Circuit de Spa-Francorchamps - Classic Pits - 2010',
  'Circuit de Spa-Francorchamps - Endurance',
  'Circuit de Spa-Francorchamps - Endurance - 2010',
  'Circuit de Spa-Francorchamps - Grand Prix Pits',
  'Circuit de Spa-Francorchamps - Grand Prix Pits - 2010',
  'Circuit des 24 Heures du Mans - 24 Heures du Mans',
  'Circuit des 24 Heures du Mans - Historic',
  'Circuit Gilles Villeneuve',
  'Circuit of the Americas - East',
  'Circuit of the Americas - Grand Prix',
  'Circuit of the Americas - NASCAR West',
  'Circuit of the Americas - West',
  'Circuit Park Zandvoort - Chicane - 2009',
  'Circuit Park Zandvoort - Club - 2009',
  'Circuit Park Zandvoort - Grand Prix - 2009',
  'Circuit Park Zandvoort - Nationaal - 2009',
  'Circuit Park Zandvoort - Oostelijk - 2009',
  'Circuit Zandvoort - Grand Prix',
  'Circuit Zandvoort - Grand Prix w/chicane',
  'Circuit Zandvoort - Nationaal',
  'Circuit Zandvoort - Oostelijk',
  'Circuit Zolder - Alternate',
  'Circuit Zolder - Grand Prix',
  'Circuito de Jerez - Ángel Nieto - Grand Prix',
  'Circuito de Jerez - Ángel Nieto - Moto',
  'Circuito de Navarra - Speed Circuit',
  'Circuito de Navarra - Speed Circuit - Medium',
  'Circuito de Navarra - Speed Circuit - Short',
  'Concord Speedway',
  'Crandon International Raceway - Full',
  'Crandon International Raceway - Short',
  'Darlington Raceway',
  'Daytona International Speedway - Moto',
  'Daytona International Speedway - Moto - 2008',
  'Daytona International Speedway - NASCAR Road',
  'Daytona International Speedway - Oval',
  'Daytona International Speedway - Oval - 2008',
  'Daytona International Speedway - Road Course',
  'Daytona International Speedway - Road Course - 2008',
  'Daytona International Speedway - Short',
  'Daytona International Speedway - Short - 2008',
  'Daytona Rallycross and Dirt Road - Dirt Road Long',
  'Daytona Rallycross and Dirt Road - Dirt Road Short',
  'Daytona Rallycross and Dirt Road - Rallycross Long',
  'Daytona Rallycross and Dirt Road - Rallycross Short',
  'Detroit Grand Prix at Belle Isle',
  'Donington Park Racing Circuit - Grand Prix',
  'Donington Park Racing Circuit - National',
  'Dover Motor Speedway',
  'EchoPark Speedway (Atlanta) - Legends Oval - 2008',
  'EchoPark Speedway (Atlanta) - Oval',
  'EchoPark Speedway (Atlanta) - Oval - 2008',
  'EchoPark Speedway (Atlanta) - Rallycross Long',
  'EchoPark Speedway (Atlanta) - Rallycross Short',
  'EchoPark Speedway (Atlanta) - Road - 2008',
  'Eldora Speedway',
  'Fairbury Speedway',
  'Federated Auto Parts Raceway at I-55',
  'Firebird Motorsports Park',
  'Five Flags Speedway',
  'Fuji International Speedway - Grand Prix',
  'Fuji International Speedway - No Chicane',
  'Hickory Motor Speedway',
  'Hockenheimring Baden-Württemberg - Grand Prix',
  'Hockenheimring Baden-Württemberg - National A',
  'Hockenheimring Baden-Württemberg - National B',
  'Hockenheimring Baden-Württemberg - Outer',
  'Hockenheimring Baden-Württemberg - Porsche Experience Center - East',
  'Hockenheimring Baden-Württemberg - Porsche Experience Center - Handling',
  'Hockenheimring Baden-Württemberg - Porsche Experience Center - Outer',
  'Hockenheimring Baden-Württemberg - Porsche Experience Center - West',
  'Hockenheimring Baden-Württemberg - Short A',
  'Hockenheimring Baden-Württemberg - Short B',
  'Homestead Miami Speedway - Open Wheel Oval',
  'Homestead Miami Speedway - Oval',
  'Homestead Miami Speedway - Road Course A',
  'Homestead Miami Speedway - Road Course B',
  'Hungaroring',
  'Huset\'s Speedway',
  'Indianapolis Motor Speedway - Bike - 2009',
  'Indianapolis Motor Speedway - NASCAR Oval',
  'Indianapolis Motor Speedway - NASCAR Oval - 2009',
  'Indianapolis Motor Speedway - Open Wheel Oval',
  'Indianapolis Motor Speedway - Open Wheel Oval - 2009',
  'Indianapolis Motor Speedway - Road Course',
  'Indianapolis Motor Speedway - Road Course - 2009',
  'Iowa Speedway - Infield Legends - 2011',
  'Iowa Speedway - Legends - 2011',
  'Iowa Speedway - Oval',
  'Iowa Speedway - Oval - 2011 - Oval - 2011',
  'Iowa Speedway - Rallycross - 2017',
  'Iowa Speedway - Road Course - 2011',
  'iRacing Superspeedway',
  'Irwindale Speedway - Figure Eight',
  'Irwindale Speedway - Figure Eight Jump',
  'Irwindale Speedway - Inner',
  'Irwindale Speedway - Outer',
  'Irwindale Speedway - Outer - Inner',
  'Kansas Speedway - Infield Road Course',
  'Kansas Speedway - Oval',
  'Kansas Speedway - Road Course',
  'Kentucky Speedway',
  'Kevin Harvick\'s Kern Raceway - Asphalt Track',
  'Kevin Harvick\'s Kern Raceway - Dirt Mini Oval',
  'Kevin Harvick\'s Kern Raceway - Dirt Track',
  'Kevin Harvick\'s Kern Raceway - Legends',
  'Knockhill Racing Circuit - International',
  'Knockhill Racing Circuit - International Reverse',
  'Knockhill Racing Circuit - National',
  'Knockhill Racing Circuit - National Reverse',
  'Knockhill Racing Circuit - Rallycross',
  'Knockhill Racing Circuit - Tri-Oval',
  'Knoxville Raceway',
  'Kokomo Speedway - Tires in',
  'Kokomo Speedway - Tires out',
  'LA Coliseum Raceway',
  'Langley Speedway',
  'Lanier National Speedway - Asphalt',
  'Lanier National Speedway - Dirt',
  'Las Vegas Motor Speedway - Infield Legends Oval',
  'Las Vegas Motor Speedway - Legends Oval',
  'Las Vegas Motor Speedway - Oval',
  'Las Vegas Motor Speedway - Road Course Combined',
  'Las Vegas Motor Speedway - Road Course Long',
  'Las Vegas Motor Speedway - Road Course Short',
  'Lernerville Speedway',
  'Limaland Motorsports Park',
  'Lime Rock Park - Chicanes',
  'Lime Rock Park - Classic',
  'Lime Rock Park - Grand Prix',
  'Lime Rock Park - School',
  'Lime Rock Park - West Bend Chicane',
  'Lincoln Speedway',
  'Long Beach Street Circuit',
  'Lucas Oil Indianapolis Raceway Park - Oval',
  'Lucas Oil Indianapolis Raceway Park - Rallycross',
  'Lucas Oil Speedway - Dirt Oval',
  'Lucas Oil Speedway - Dirt Road',
  'Lånkebanen (Hell RX) - Club',
  'Lånkebanen (Hell RX) - Hell Rallycross',
  'Lånkebanen (Hell RX) - Rallycross Short',
  'Lånkebanen (Hell RX) - Road Long',
  'Lånkebanen (Hell RX) - Road Short',
  'Martinsville Speedway',
  'Miami International Autodrome - Extended Marina Loop',
  'Miami International Autodrome - Extended MIA Loop',
  'Miami International Autodrome - Grand Prix',
  'Miami International Autodrome - Marina Loop',
  'Miami International Autodrome - MIA Loop',
  'Michigan International Speedway',
  'Mid-Ohio Sports Car Course - Alt Oval',
  'Mid-Ohio Sports Car Course - Chicane',
  'Mid-Ohio Sports Car Course - Full Course',
  'Mid-Ohio Sports Car Course - Oval',
  'Mid-Ohio Sports Car Course - Short',
  'Millbridge Speedway',
  'Misano World Circuit Marco Simoncelli - Club',
  'Misano World Circuit Marco Simoncelli - Grand Prix',
  'Misano World Circuit Marco Simoncelli - Grand Prix - 2007',
  'Misano World Circuit Marco Simoncelli - Grand Prix - Historic Reverse',
  'Misano World Circuit Marco Simoncelli - Truck',
  'Mobility Resort Motegi - East',
  'Mobility Resort Motegi - Grand Prix',
  'Mobility Resort Motegi - Oval',
  'Mobility Resort Motegi - West',
  'MotorLand Aragón - Grand Prix',
  'MotorLand Aragón - Motorcycle Grand Prix',
  'MotorLand Aragón - Motorcycle National',
  'MotorLand Aragón - National',
  'MotorLand Aragón - Outer',
  'MotorLand Aragón - Touring Car',
  'MotorLand Aragón - West',
  'Motorsport Arena Oschersleben - Alternate',
  'Motorsport Arena Oschersleben - B Course',
  'Motorsport Arena Oschersleben - C Course',
  'Motorsport Arena Oschersleben - Grand Prix',
  'Mount Panorama Circuit',
  'Mount Washington Hillclimb - Descent',
  'Mount Washington Hillclimb - Hillclimb',
  'Myrtle Beach Speedway',
  'Nashville Fairgrounds Speedway - Mini',
  'Nashville Fairgrounds Speedway - Oval',
  'Nashville Superspeedway',
  'New Hampshire Motor Speedway - Legends',
  'New Hampshire Motor Speedway - Oval',
  'New Hampshire Motor Speedway - Road Course',
  'New Hampshire Motor Speedway - Road Course with North Oval',
  'New Hampshire Motor Speedway - Road Course with South Oval',
  'New Jersey Motorsports Park - Thunderbolt',
  'New Jersey Motorsports Park - Thunderbolt w/both chicanes',
  'New Jersey Motorsports Park - Thunderbolt w/first chicane',
  'New Jersey Motorsports Park - Thunderbolt w/second chicane',
  'New Smyrna Speedway',
  'North Wilkesboro Speedway - Oval',
  'North Wilkesboro Speedway - Oval - 1987',
  'Nürburgring Combined - Gesamtstrecke 24h',
  'Nürburgring Combined - Gesamtstrecke Long',
  'Nürburgring Combined - Gesamtstrecke Short w/out Arena',
  'Nürburgring Combined - Gesamtstrecke VLN',
  'Nürburgring Grand-Prix-Strecke - BES/WEC',
  'Nürburgring Grand-Prix-Strecke - Grand Prix',
  'Nürburgring Grand-Prix-Strecke - Grand Prix w/out Arena',
  'Nürburgring Grand-Prix-Strecke - Kurzanbindung w/out Arena',
  'Nürburgring Grand-Prix-Strecke - Müllenbachschleife',
  'Nürburgring Grand-Prix-Strecke - Sprintstrecke',
  'Nürburgring Nordschleife - Industriefahrten',
  'Nürburgring Nordschleife - Touristenfahrten',
  'Okayama International Circuit - Full Course',
  'Okayama International Circuit - Short',
  'Oran Park Raceway - Grand Prix',
  'Oran Park Raceway - Moto',
  'Oran Park Raceway - North',
  'Oran Park Raceway - North A',
  'Oran Park Raceway - North B',
  'Oran Park Raceway - South',
  'Oswego Speedway - Dirt',
  'Oswego Speedway - Mini Oval',
  'Oswego Speedway - Oval',
  'Oulton Park Circuit - Fosters',
  'Oulton Park Circuit - Fosters w/Hislop',
  'Oulton Park Circuit - International',
  'Oulton Park Circuit - Intl w/no Chicanes',
  'Oulton Park Circuit - Intl w/out Brittens',
  'Oulton Park Circuit - Intl w/out Hislop',
  'Oulton Park Circuit - Island',
  'Oulton Park Circuit - Island Historic',
  'Oxford Plains Speedway',
  'Phillip Island Circuit',
  'Phoenix Raceway - Oval',
  'Phoenix Raceway - Oval w/open dogleg',
  'Pocono Raceway',
  'Port Royal Speedway',
  'Portland International Raceway - Full Circuit',
  'Portland International Raceway - No Chicane',
  'Qualcomm Circuit (Naval Base Coronado)',
  'Red Bull Ring - Grand Prix',
  'Red Bull Ring - National',
  'Red Bull Ring - North',
  'Richmond Raceway',
  'Road America - Bend',
  'Road America - Full Course',
  'Road America - Short East',
  'Road America - Short West',
  'Road Atlanta - Club',
  'Road Atlanta - Full Course',
  'Road Atlanta - Short',
  'Rockingham Speedway - Infield Road Course',
  'Rockingham Speedway - Oval',
  'Rockingham Speedway - Oval - 2012',
  'Rockingham Speedway - Road Course',
  'Rockingham Speedway - Short Road Course',
  'Rudskogen Motorsenter',
  'Sachsenring',
  'Sandown International Motor Raceway',
  'Sebring International Raceway - Club',
  'Sebring International Raceway - International',
  'Sebring International Raceway - Modified',
  'Shell V-Power Motorsport Park at The Bend - East Circuit',
  'Shell V-Power Motorsport Park at The Bend - GT Circuit',
  'Shell V-Power Motorsport Park at The Bend - International Circuit',
  'Shell V-Power Motorsport Park at The Bend - South West Circuit',
  'Shell V-Power Motorsport Park at The Bend - Sprint Circuit',
  'Shell V-Power Motorsport Park at The Bend - West Circuit',
  'Shell V-Power Motorsport Park at The Bend - West Plus Circuit',
  'Silverstone Circuit - Grand Prix',
  'Silverstone Circuit - International',
  'Silverstone Circuit - National',
  'Slinger Speedway - Figure 8',
  'Slinger Speedway - Oval',
  'Snetterton Circuit - 100',
  'Snetterton Circuit - 200',
  'Snetterton Circuit - 300',
  'Sonoma Raceway - Cup Long',
  'Sonoma Raceway - Cup Short',
  'Sonoma Raceway - Indycar 2005-2007',
  'Sonoma Raceway - Indycar 2008-2011',
  'Sonoma Raceway - Indycar 2012-2018',
  'Sonoma Raceway - Oval',
  'Sonoma Raceway - Rallycross',
  'Sonoma Raceway - Short',
  'Sonoma Raceway - Sportscar',
  'Sonoma Raceway - Sportscar Alt',
  'South Boston Speedway',
  'Southern National Motorsports Park',
  'St. Petersburg Grand Prix',
  'Stafford Motor Speedway',
  'Summit Point Raceway - Jefferson Circuit',
  'Summit Point Raceway - Jefferson Reverse',
  'Summit Point Raceway - School',
  'Summit Point Raceway - Short',
  'Summit Point Raceway - Summit Point Raceway',
  'Suzuka International Racing Course - East',
  'Suzuka International Racing Course - Grand Prix',
  'Suzuka International Racing Course - Moto',
  'Suzuka International Racing Course - West',
  'Suzuka International Racing Course - West w/chicane',
  'Talladega Superspeedway',
  'Texas Motor Speedway - Legends Oval',
  'Texas Motor Speedway - Oval',
  'The Bullring',
  'The Dirt Track at Charlotte',
  'The Milwaukee Mile - Oval',
  'The Milwaukee Mile - Road Course',
  'Thompson Speedway Motorsports Park',
  'Thruxton Circuit',
  'Tsukuba Circuit - 1000 Chicane',
  'Tsukuba Circuit - 1000 Full',
  'Tsukuba Circuit - 1000 Full Reverse',
  'Tsukuba Circuit - 1000 Outer',
  'Tsukuba Circuit - 2000 Full',
  'Tsukuba Circuit - 2000 Moto',
  'Tsukuba Circuit - 2000 Short',
  'USA International Speedway - Asphalt',
  'USA International Speedway - Dirt',
  'Virginia International Raceway - Full Course',
  'Virginia International Raceway - Grand Course',
  'Virginia International Raceway - North Course',
  'Virginia International Raceway - Patriot Course',
  'Virginia International Raceway - South Course',
  'Volusia Speedway Park',
  'Watkins Glen International - Boot',
  'Watkins Glen International - Classic',
  'Watkins Glen International - Classic Boot',
  'Watkins Glen International - Cup',
  'WeatherTech Raceway at Laguna Seca - 2026',
  'Weedsport Speedway',
  'Wild West Motorsports Park',
  'Williams Grove Speedway',
  'Willow Springs International Raceway',
  'Winton Motor Raceway - Club Circuit',
  'Winton Motor Raceway - National Circuit',
  'Winton Motor Raceway - Rallycross',
  'World Wide Technology Raceway (Gateway) - Oval',
  'World Wide Technology Raceway (Gateway) - Road Course'
];

/** Fold diacritics + lowercase + strip non-alphanumerics for fuzzy matching. */
function foldNorm(s: string): string {
  return (s || "")
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]/g, "");
}

function wordTokens(s: string): string[] {
  return (s || "")
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .toLowerCase()
    .split(/[^a-z0-9]+/)
    .map((t) => t.replace(/[^a-z0-9]/g, ""))
    .filter((t) => t.length > 1);
}

/**
 * Unambiguous filename-token -> roster entry aliases for names iRacing words
 * differently than the community does (checked against the roster above).
 */
const ROSTER_ALIASES: [string, string][] = [
  ["mosport", "Canadian Tire Motorsports Park"],
  ["amvalkyrie", "Aston Martin Valkyrie AMR-LMH"],
  ["mx52016", "Global Mazda MX-5 Cup"],
];

/**
 * Split an iRacing "{car}_{track} {date}.ibt" filename into its car/track parts.
 * Falls back to the whole basename when the pattern doesn't match.
 */
export function splitIracingFilename(filename: string): { carPart: string; trackPart: string } {
  let base = (filename || "").replace(/\.[^.]+$/, "");
  base = base.replace(/\s+\d{4}-\d{2}-\d{2}\s+\d{2}[-:]\d{2}[-:]\d{2}.*$/, "");
  const us = base.indexOf("_");
  if (us < 0) return { carPart: base, trackPart: base };
  return { carPart: base.slice(0, us), trackPart: base.slice(us + 1) };
}

/**
 * Best-effort match of a filename segment against an iRacing roster list.
 * 1. Normalized containment (exactly one roster entry contains the segment or vice versa).
 * 2. Token-overlap scoring: a roster token counts when it appears inside a filename
 *    token; needs >= 2 hits and a strict winner (ties prefer non-"[Legacy]" entries).
 * Returns null when ambiguous — the user picks from the dropdown instead.
 */
export function snapToRoster(segment: string, roster: string[]): string | null {
  const sn = foldNorm(segment);
  if (!sn) return null;

  // 0. Explicit aliases for unambiguous iRacing naming mismatches.
  for (const [alias, entry] of ROSTER_ALIASES) {
    if (sn.includes(alias) && roster.includes(entry)) return entry;
  }

  const contained = roster.filter((r) => {
    const rn = foldNorm(r);
    return rn && (rn.includes(sn) || sn.includes(rn));
  });
  if (contained.length === 1) return contained[0];

  const segTokens = wordTokens(segment);
  if (segTokens.length === 0) return null;
  let best: string | null = null;
  let bestScore = -Infinity;
  let tied = false;
  for (const entry of roster) {
    const eTokens = Array.from(new Set(wordTokens(entry)));
    let hits = 0;
    for (const et of eTokens) {
      if (segTokens.some((st) => st.includes(et) || et.includes(st))) hits++;
    }
    if (hits < 2) continue;
    const score = hits - (entry.startsWith("[Legacy]") ? 0.5 : 0);
    if (score > bestScore) {
      bestScore = score;
      best = entry;
      tied = false;
    } else if (score === bestScore) {
      tied = true;
    }
  }
  return tied ? null : best;
}
