// Build step: inline the Next.js static export (out/*) into
// api/lib/web-dist.ts as base64. The function serves these at / — no
// filesystem access needed at runtime, so it works however `neon deploy`
// bundles the function.
import { readdirSync, readFileSync, writeFileSync, statSync, existsSync, mkdirSync } from "node:fs";
import { join, relative, sep, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(fileURLToPath(new URL(".", import.meta.url)), "..");
const dist = join(root, "..", "out");
const out = join(root, "api", "lib", "web-dist.ts");

if (!existsSync(dist)) {
  console.error(`out/ not found — run the static build first (bash scripts/build-static.sh)`);
  process.exit(1);
}

const files = {};
function walk(dir) {
  for (const e of readdirSync(dir)) {
    const p = join(dir, e);
    // Large bridge binaries are hosted on GitHub Releases, not embedded —
    // embedding a 34MB zip would 50x the function bundle and break deploys.
    if (p.includes(`${sep}downloads${sep}`) || p.endsWith(`${sep}downloads`)) continue;
    if (statSync(p).isDirectory()) walk(p);
    else files[relative(dist, p).split(sep).join("/")] = readFileSync(p).toString("base64");
  }
}
walk(dist);

const names = Object.keys(files).sort();
let total = 0;
for (const n of names) total += files[n].length;

const ts = `// AUTO-GENERATED by neon/scripts/embed-web.mjs — do not edit.
// ${names.length} files, ~${Math.round(total / 1024)} KB base64, built ${new Date().toISOString()}.
export const webAssets: Record<string, string> = {
${names.map((n) => `  ${JSON.stringify(n)}: ${JSON.stringify(files[n])},`).join("\n")}
};
`;
mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, ts);
console.log(`wrote ${out}: ${names.length} files, ~${Math.round(total / 1024)} KB`);
